
lane :tests do
  run_tests(scheme: "nRF-ToolboxTests")
end

lane :version do
  last_tag = sh("git describe --tags --abbrev=0").strip
  version_name = last_tag.gsub("v", "")
  
  commit_count = sh("git rev-list --count HEAD").strip.to_i
  
  now = Time.now.getutc
  yy = now.year % 100
  mm = format("%02d", now.month)
  dd = format("%02d", now.day)
  revisions = format("%02d", commit_count % 100)
  version_code = "#{yy}#{mm}#{dd}#{revisions}"

  UI.message("Setting iOS version:")
  UI.message("Version name: #{version_name}")
  UI.message("Version code: #{version_code}")
  
  increment_version_number_in_plist(
    version_number: version_name,
    target: "nRF-Toolbox"
  )
  
  increment_version_number_in_xcodeproj(
    version_number: version_name,
    target: "nRF-Toolbox"
  )
  
  increment_version_number(
    version_number: version_name,
    xcodeproj: "nRF Toolbox.xcodeproj"
  )

  increment_build_number(
    build_number: version_code,
    xcodeproj: "nRF Toolbox.xcodeproj"
  )
end

lane :authenticate do
  api_key = app_store_connect_api_key(
    key_id: ENV["APPLE_KEY_ID"],
    issuer_id: ENV["APPLE_ISSUER_ID"],
    key_content: ENV["APPLE_P8"],
    is_key_content_base64: true,
    duration: 1200,
    in_house: false
  )
  
  api_key
end

def ensure_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
  create_keychain(
    name: name,
    password: ENV["MATCH_KEYCHAIN_PASSWORD"],
    default_keychain: true,
    unlock: true,
    timeout: 0,
    lock_when_sleeps: false,
    add_to_search_list: true
  )
end

lane :unlock_db do
  sh("security unlock-keychain -p #{ENV["MATCH_KEYCHAIN_PASSWORD"]} fastlane-db")
  sh("security default-keychain -s fastlane-db")
end

lane :build do
  path = build_app(
    scheme: "nRF-Toolbox",
    export_method: "app-store",
  )
  
  path
end

lane :upload_testflight do
  tests
  version
  api_key = authenticate

  ensure_keychain('fastlane');
  unlock_db

  match(
    type: "appstore",
    keychain_name: "fastlane",
    keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
    app_identifier: "com.nordicsemi.nRF-Toolbox",
    readonly: true
  )
  
  path = build
  
  pilot(
    api_key: api_key,
    ipa: path,
  )
end

lane :screenshots do
  capture_screenshots
end

lane :release do
  tests
  version
  screenshots
  frame_screenshots
  api_key = authenticate
  
  ensure_keychain('fastlane');
  unlock_db

  match(
    type: "appstore",
    keychain_name: "fastlane",
    keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
    app_identifier: "com.nordicsemi.nRF-Toolbox",
    readonly: true
  )
  
  path = build
  
  deliver(
    submit_for_review: false,
    api_key: api_key,
    ipa: path,
    force: true,
    precheck_include_in_app_purchases: false,
    screenshots_path: "./fastlane/screenshots",
    overwrite_screenshots: true
  )
end
